title: Karissa Mengle # your name (or website title) here
logo: "/images/myself_jpg.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am currently a graduate student pursuing a Masters of Science in Geospatial Technologies from the University of Oklahoma.
  I have a Bachelors of Science degree in Environmental Biology from California State Polytechnic University, Pomona.
  <br><br>
  # Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/karissa-mengle">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
